swagger: "2.0"
info:
  version: "1.0.0"
  title: Health Check Dashboard
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /health/ping:
    x-swagger-router-controller: health
    get:
      description: Returns current status of all services
      # used as the method name of the controller
      operationId: ping
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/PingResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /health/stats:
    x-swagger-router-controller: health
    get:
      description: Returns health status over the last hour (with 1 minute interval)
      # used as the method name of the controller
      operationId: getStats
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/StatsResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  Service:
    type: object
    required:
      - status
      - details
      - serviceName
    properties:
      status:
        type: string
        enum:
          - ok
          - error
      details:
        type: object
      serviceName:
        type: string
  Services:
    type: array
    items:
      $ref: "#/definitions/Service"
  PingResponse:
    required:
      - status
      - services
    properties:
      status:
        type: string
        enum:
         - ok
         - error
      services:
        $ref: "#/definitions/Services"
  StatsResponse:
    required:
      - uptimePercent
    properties:
      uptimePercent:
        type: number
        minimum: 0
        maximum: 100
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
